# Generated by Django 2.0.5 on 2018-09-22 22:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(choices=[('bangladesh', '1. bangladesh')], max_length=100)),
                ('country_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('company_id', models.IntegerField(default=0)),
                ('details', models.TextField()),
                ('details_id', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('scanning', models.BooleanField(default=False)),
                ('barcode_id', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('packet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medicine.MedicinePacket')),
            ],
        ),
    ]
