# Generated by Django 2.0.5 on 2018-09-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcoderead',
            name='barcode_id',
        ),
        migrations.AddField(
            model_name='barcoderead',
            name='scanning_id',
            field=models.IntegerField(default=0),
        ),
    ]
