# Generated by Django 2.0.5 on 2018-09-24 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_remove_medicine_medicine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinepacket',
            name='packet_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
